### PR TITLE
Fix display of GxAirCom  in Safari OSX/iPhone/iPad

### PR DESCRIPTION
**Pull request by rvt**
For iPad and iPhone I noticed that when I try to open the webpages of GxAirCom on these devices the pages get's downloaded instead of displayed.

This is because the `Content-Disposition` is set to  `inline: filename="<somefile>.html.gz` so apparently Safari thinks this is a '.gz' file that cannot be displayed. Event though `Content-Type` is `text/html`. I think the jury is out if how this should be interpreted... 

That said, the fix is in in `ESPAsyncWebServer`, this library seems to be unmaintained (see https://github.com/me-no-dev/ESPAsyncWebServer) , it also did not had any options to set our own  `Content-Disposition` so it seemed for to add the fix in that library..

The fix is simply to remove the `Content-Disposition` for files that should be displayed.

### CODE REVIEW

**Comment by VirusPilot** [comment]
After adding your change both Chrome and Safari won't show any website at all.

**Comment by rvt** [comment]
I did a compare again and I cannot replicate this, I tested this with chrome, Safari and Edge.

Can you let me know the output of `curl -vvv http://192.168.4.1/info.html --output /tmp/out.gz`

I get:
```bash
rvt@computer ~ % curl -vvv http://192.168.4.1/info.html --output /tmp/out.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.4.1:80...
* Connected to 192.168.4.1 (192.168.4.1) port 80 (#0)
> GET /info.html HTTP/1.1
> Host: 192.168.4.1
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 2535
< Content-Type: text/html
< Content-Encoding: gzip
< Connection: close
< Accept-Ranges: none
< 
{ [1306 bytes data]
100  2535  100  2535    0     0  14270      0 --:--:-- --:--:-- --:--:-- 14824
* Closing connection 0
* ```

**Comment by TomBric** [comment]
I also tested the GxAirCom on the IPad (Safari and Chorme): The browser tried to download index.html.gz insted of displaying the page in the web browser. rvt's suggestion should do the trick.

**Comment by gereic** [comment]
Can you try with latest code (Binarys) ?

**Comment by TomBric** [comment]
Thanks, web interface is now working with 5.4.0 on the ipad

**Pull request merged**
