### PR TITLE
This PR adds support for wind measurements via ADS1015

### PR DESCRIPTION
**Pull request by bzed**
Using an Pimoroni ADS1015 board is expected (or a similar ads1015 setup).
https://shop.pimoroni.com/products/ads1015-adc-breakout

This allows measuring wind speed / direction from sensors with - for example - 0-10V output. 0-20 mA or 4-20mA sensors will work, too, with additional appropriate resistors or using a Knick Varitrans P 15000 H1. Using the Knick Varitrans also allows to add gxaircom to existing installations without disturbing the other measurements.

### CODE REVIEW

**Comment by bzed** [comment]
I've started to work on the PR before you've compressed the html parts, so I've started to reduce the size, I've kept the changes in the PR, hope thats okay.

**Comment by gereic** [comment]
Is this already working ??
I found that comment.
 // don't use ADS1015 or things will break.

**Comment by gereic** [comment]
added your commit in the master-branch.
Can you try it ?

**Comment by bzed** [comment]
> Is this already working ?? I found that comment. // don't use ADS1015 or things will break.

Sorry for the late reply - the comment just means that the build will break if you use ADS1015 as name in the enum. And the failure is non-obvious :)

**Comment by bzed** [comment]
> added your commit in the master-branch. Can you try it ?

Thanks! will do when I'm back at my tech playground

**Pull request closed without merging**
